Nama  : San Antonio Limbong

NIM   : 12S19033

## Latihan 1 | Data Cleaning – Part I

### Latihan 1.1 | Handling Missing Data

#### Latihan 1.1.1 | Recode/Replace

Fungsi fillna pada pandas berguna untuk mengkode ulang nilai yang hilang ke nilai lain

In [1]:
import pandas as pd
ebola = pd.read_csv('C:/Users/ASUS/a semester 7/DAMI/New folder/data/data/country_timeseries.csv')
print(ebola.fillna(0).iloc[0:10, 0:5])

         Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone
0    1/5/2015  289        2776.0            0.0            10030.0
1    1/4/2015  288        2775.0            0.0             9780.0
2    1/3/2015  287        2769.0         8166.0             9722.0
3    1/2/2015  286           0.0         8157.0                0.0
4  12/31/2014  284        2730.0         8115.0             9633.0
5  12/28/2014  281        2706.0         8018.0             9446.0
6  12/27/2014  280        2695.0            0.0             9409.0
7  12/24/2014  277        2630.0         7977.0             9203.0
8  12/21/2014  273        2597.0            0.0             9004.0
9  12/20/2014  272        2571.0         7862.0             8939.0


#### Latihan 1.1.2 | Fill Forward

Fungsi fillna diikuti dengan methode ffill digunakan untuk mengisi maju suatu sel, sehingga nilai terakhir yang diketahui digunakan untuk mengganti nilai yang hilang berikutnya.Dengan cara ini, nilai yang hilang diganti dengan nilai yang diketahui / dicatat
terakhir

In [2]:
print(ebola.fillna(method='ffill').iloc[0:10, 0:5])

         Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone
0    1/5/2015  289        2776.0            NaN            10030.0
1    1/4/2015  288        2775.0            NaN             9780.0
2    1/3/2015  287        2769.0         8166.0             9722.0
3    1/2/2015  286        2769.0         8157.0             9722.0
4  12/31/2014  284        2730.0         8115.0             9633.0
5  12/28/2014  281        2706.0         8018.0             9446.0
6  12/27/2014  280        2695.0         8018.0             9409.0
7  12/24/2014  277        2630.0         7977.0             9203.0
8  12/21/2014  273        2597.0         7977.0             9004.0
9  12/20/2014  272        2571.0         7862.0             8939.0


#### Latihan 1.1.3 | Fill Backward

Fungsi fillna diikuti dengan methode bfill digunakan untuk mengisi mundur suatu sel, sehingga nilai terakhir yang diketahui digunakan untuk mengganti nilai yang hilang sebelumnya.Dengan cara ini, nilai yang hilang diganti dengan nilai terbaru

In [3]:
print(ebola.fillna(method='bfill').iloc[:,0:5].tail())

          Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone
117  3/27/2014    5         103.0            8.0                6.0
118  3/26/2014    4          86.0            NaN                NaN
119  3/25/2014    3          86.0            NaN                NaN
120  3/24/2014    2          86.0            NaN                NaN
121  3/22/2014    0          49.0            NaN                NaN


#### Latihan 1.1.4 | Interpolate 

Fungsi interpolate berguna mengisi nilai yang hilang secara linear

In [4]:
print(ebola.interpolate().iloc[0:10,0:5])

         Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone
0    1/5/2015  289        2776.0            NaN            10030.0
1    1/4/2015  288        2775.0            NaN             9780.0
2    1/3/2015  287        2769.0         8166.0             9722.0
3    1/2/2015  286        2749.5         8157.0             9677.5
4  12/31/2014  284        2730.0         8115.0             9633.0
5  12/28/2014  281        2706.0         8018.0             9446.0
6  12/27/2014  280        2695.0         7997.5             9409.0
7  12/24/2014  277        2630.0         7977.0             9203.0
8  12/21/2014  273        2597.0         7919.5             9004.0
9  12/20/2014  272        2571.0         7862.0             8939.0


#### Latihan 1.1.5 | Drop Missing Values 

Metode dropna untuk menghilangkan data yang hilang dan menentukan parameter fungsi yang mengontrol bagaimana data akan dihilangkan.

In [5]:
print(ebola.shape)

(122, 18)


In [6]:
ebola_dropna = ebola.dropna()
print(ebola_dropna.shape)

(1, 18)


In [7]:
print(ebola_dropna)

          Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone  \
19  11/18/2014  241        2047.0         7082.0             6190.0   

    Cases_Nigeria  Cases_Senegal  Cases_UnitedStates  Cases_Spain  Cases_Mali  \
19           20.0            1.0                 4.0          1.0         6.0   

    Deaths_Guinea  Deaths_Liberia  Deaths_SierraLeone  Deaths_Nigeria  \
19         1214.0          2963.0              1267.0             8.0   

    Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  Deaths_Mali  
19             0.0                  1.0           0.0          6.0  


### Latihan 1.2 | Handling Noisy Data

In [8]:
import numpy as np
import math

a = [4, 8, 9, 15, 21, 21, 24, 25, 26, 28, 29, 34] #array
sa = np.sort(a) # sorted array

In [9]:
# create bins
bin_mean = np.zeros((3,4))
bin_boundaries = np.zeros((3,4))
bin_median = np.zeros((3,4))

Smoothing by bin mean

Berfungsi untuk mengatasi nilai yang kosong dengan nilai rata-rata pada bin tersebut

In [10]:
# Bin mean
for i in range (0,12,4):
    k = int(i/4)
    mean = (sa[i] + sa[i+1] + sa[i+2] + sa[i+3])/4
    for j in range(4):
        bin_mean[k,j] = mean
print("Bin Mean: \n", bin_mean)

Bin Mean: 
 [[ 9.    9.    9.    9.  ]
 [22.75 22.75 22.75 22.75]
 [29.25 29.25 29.25 29.25]]


Smoothing by bin boundaries

Berfungsi untuk mengatasi nilai yang kosong dengan nilai terendah/tertinggi terdekat

In [11]:
# Bin boundaries
for i in range (0,12,4):
    k = int(i/4)
    for j in range(4):
        if (sa[i+j]-sa[i]) < (sa[i+3]-sa[i+j]):
            bin_boundaries[k,j] = sa[i]
        else:
            bin_boundaries[k,j] = sa[i+3]
print("Bin Boundaries: \n", bin_boundaries)

Bin Boundaries: 
 [[ 4.  4.  4. 15.]
 [21. 21. 25. 25.]
 [26. 26. 26. 34.]]


Smoothing by bin median

Berfungsi untuk mengatasi nilai yang kosong dengan nilai tengah pada bin tersebut

In [12]:
# Bin median
for i in range (0,12,4):
    k = int(i/4)
    for j in range(4):
        bin_median[k,j] = sa[i+2]
print("Bin Median: \n", bin_median)

Bin Median: 
 [[ 9.  9.  9.  9.]
 [24. 24. 24. 24.]
 [29. 29. 29. 29.]]
